config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :vehicules, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :show, :create]
    # index & show à supprimer, uniquement pour les tests dans un premier temps
  end

  resource :bookings, only: [] do
    member do
      patch ":id/accept", to: "bookings#accept", as: :accept
      patch ":id/decline", to: "bookings#decline", as: :decline
    end
  end

  get '/dashboard', to: "pages#dashboard"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  attr_accessor :date_resa
  belongs_to :user
  belongs_to :vehicule


  validates :user_id, presence: true
  validates :vehicule_id, presence: true
  validates :date_debut, presence: true
  # validates :date_fin, presence: true, comparison: { greater_than_or_equal_to: :date_debut }
  validates :total_prix, presence: true, comparison: { greater_than: 0 }

end

app/models/concerns/vehicule_concern.rb
module VehiculeConcern
  def booked_dates
    # renvoie un array d'array des dates de debut et de fin de tous les bookings du véhicule
    bookings.pluck(:date_debut, :date_fin)
  end

  def simple_format_booked_dates
    # renvoie un array d'array des dates de debut et de fin
    # de tous les bookings du pokemon mais sous la forme stringifiée : "1991-12-28"
    booked_dates.deep_map(&:to_s)
  end

  def booked_dates_json_objects
    simple_format_booked_dates.map do |dates_arr|
      {
        from: dates_arr.first,
        to: dates_arr.last
      }
    end
  end

  def flatpickr_booked_dates_object
    {
      dateFormat: "Y-m-d",
      disable: booked_dates_json_objects
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :vehicules
  has_many :bookings
  has_many :requested_bookings, through: :vehicules, source: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
end

app/models/vehicule.rb
class Vehicule < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy

  validates :user_id, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include VehiculeConcern
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  end
  def show
  end
  def new

  end
  def create
    @vehicule = Vehicule.find(params[:vehicule_id])
    @booking = Booking.new(booking_params)

    @booking.date_debut = @booking.date_resa[0,10].to_date
    @booking.date_fin  = @booking.date_resa[-10,10].to_date
    @booking.vehicule = @vehicule
    @booking.total_prix = (@booking.date_fin - @booking.date_debut).to_i * @vehicule.prix
    @booking.user = current_user
    if @booking.save!
    redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end

  end



  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to dashboard_path, status: :see_other
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to dashboard_path, status: :see_other
  end



  private

  def booking_params
    params.require(:booking).permit(:commentaire, :date_resa)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @vehicule = Vehicule.new
  end

  def dashboard
    @vehicules = current_user.vehicules
    #resa pour mes véhicules
    @requested_bookings = current_user.requested_bookings

    #mes résa pour des véhicules tiers
    @bookings = current_user.bookings
  end
end

app/controllers/vehicules_controller.rb
class VehiculesController < ApplicationController
  def index
    @vehicules = Vehicule.all
      if params[:query].present?
        @vehicules = @vehicules.where("category ILIKE ?", "%#{params[:query]}%")
      end
    @markers = @vehicules.geocoded.map do |vehicule|
      {
        lat: vehicule.latitude,
        lng: vehicule.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {vehicule: vehicule})
      }
    end
  end

  def show
    @vehicule = Vehicule.find(params[:id])
    @booking = Booking.new

  end

  def new
    @vehicule = Vehicule.new
  end

  def create
    @vehicule = Vehicule.new(vehicule_params)
    @vehicule.user = current_user
    @vehicule.save!
    redirect_to vehicules_path(@vehicules)
  end

  def update
  end
  def edit
  end

  def destroy
    @vehicule = Vehicule.find(params[:id])
    @vehicule.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def vehicule_params
    params.require(:vehicule).permit(:category, :model, :description, :prix, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h3>Votre réservation est confirmée.</h3>
<p> Vous allez recevoir un mail de confirmation avec les modalités pour contacter le propriétaire</p>

app/views/bookings/index.html.erb
<h1>Tous les bookings (vue uniquement pour les administrateurs)</h1>


<br>
<%= link_to "Home page", root_path %>

app/views/bookings/show.html.erb
<h1>Partial permettant le show d'un booking</h1>


<br>
<%= link_to "Home page", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      /* @import url('https://fonts.googleapis.com/css2?family=Gothic+A1:wght@100;200;300;400;500&display=swap'); */

    </style>
    <title>Carconnect</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
 <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
  <div class="container">


<div class="meslocations">

    <h2>mes locations</h2>
      <div class="card-grid">

          <% @bookings.each do |booking| %>
            <div class="card-grid-item d-flex flex-column">
              <div class="card-product">
                <%= image_tag booking.vehicule.photo.url, crop: :fill, height: 200, width: 200,  class: "card_image"%>
                <div class="model">
                <div class="top d-flex justify-content-between">
                  <h2 class="m-0"><%= booking.vehicule.model%> </h2>
                </div>
                <div>
                  <p><strong>Total location : </strong><%= booking.total_prix%> $</p>
                  <p><strong>Date debut:</strong> <%= booking.date_debut %></p>
                  <p><strong>Date du fin:</strong> <%= booking.date_fin %></p>
                  <p><strong> status:</strong> <%= booking.status %></p>
                  <p><strong>TO: </strong><%= booking.user.email %>&nbsp;&nbsp;&nbsp;

                  <%= link_to "decline",
                      decline_bookings_path(booking),
                      data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}
                  %>
                  </p>
                </div>
              </div>
              </div>
            </div>
          <% end %>

        </div>
    </div>




<div class="mesvehicules">
    <%# mes voitures %>
  <h2>Mes voitures à louer</h2>
  <div class="card-grid">

      <% @vehicules.each do |vehicule| %>
      <div class="card-grid-item d-flex flex-column">
        <div class="card-product">
          <%= image_tag vehicule.photo.url, crop: :fill, height: 200, width: 200,  class: "card_image"%>
          <div class="model">
            <div class="top d-flex justify-content-between">
              <h2 class="m-0"><%= vehicule.model%> </h2>
            </div>
            <div class="category">
              <p><%= vehicule.category  %> <br>
            </div>
            <div class="description">
              <%= vehicule.description %>
            </div>
            <div class="price">
              <%= vehicule.prix%></b>$/jour</p>
            </div>
          </div>
              <%= link_to "Delete",
                vehicule_path(vehicule),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
            %>
        </div>
      </div>
      <% end %>

  </div>
</div>

    <%# locations de mes voitures %>

    <h2>Les locations de mes véhicules</h2>
    <div class="card-grid">

        <% @requested_bookings.each do |booking| %>
          <div class="card-grid-item d-flex flex-column">
            <div class="card-product">
              <%= image_tag booking.vehicule.photo.url, crop: :fill, height: 200, width: 200,  class: "card_image"%>
              <div class="model">
                <div class="top d-flex justify-content-between">
                  <h2 class="m-0"><%= booking.vehicule.model%> </h2>
                </div>
                <div class="price">
                  <p><%= booking.vehicule.prix%>$/jour</p>
                </div>
                <p><strong>Date debut:</strong> <%= booking.date_debut %>,</p>
                <p><strong>Date du fin:</strong> <%= booking.date_fin %>,</p>
                <p><strong> status:</strong> <%= booking.status %></p>
                <p><strong>TO: </strong><%= booking.user.email %>&nbsp;&nbsp;&nbsp;
                <% if booking.status == 'pending' %>
                  <%= link_to "accept",
                    accept_bookings_path(booking),
                    data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}
                  %>&nbsp;
                  <%= link_to "decline",
                      decline_bookings_path(booking),
                      data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}
                  %>
                <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>

    </div>

</div>

app/views/pages/home.html.erb
  <div class = "mt-2 fw-bold text-center mb-3">
  </div>
<div class="container-home">
    <div class= "ms-3 align-self-center text-center" id="description-home" style="width: 100%;">
      <h1> Soyez Funky ! </h1>
      <h3 class="mb-3"> Louez un véhicule pas comme les autres </h3>
      <ul>
      <iframe width="700" height="450" src="https://www.youtube.com/embed/OPf0YbXqDm0?autoplay=1&si=ooRsegGRIUAPaSH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>    <div class="d-flex justify-content-between" id="main">
      </ul>

    <a class="learn-more"  href="./vehicules"> Nos Vehicules les plus Hot ! </a>
    </div>

    <div class="d-inline-grid justify-content-center" >
        <div class="images-home">




        </div>

        </div>
      </div>


    </div>

app/views/shared/_card.html.erb
    <div class="col-lg-8 col-xl-13 ">
        <div class="card-product">
          <%= cl_image_tag vehicule.photo.key, class: "img-fluid", crop: :fill %>
          <div class="card-product-infos">
            <div class="top">
              <h2 class="m-0"><%= vehicule.model %> </h2>
              <%= image_tag "car.jpg", class: "icon"%>
            </div>
            <p><%= vehicule.category  %> <br> <%= vehicule.description %> <br><b><%= vehicule.prix%></b>$/jour</p>
          </div>
        </div>
      </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
       <%= image_tag "carconnect_logo.svg"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active"></li>
          <li class="nav-item"> <%= link_to "Louer", vehicules_path, class: "nav-link" %> </li>
          <li> <%= link_to "Ajouter un véhicule", new_vehicule_path, class: "nav-link" %> </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

            <%= image_tag "omar_sy.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Voir les véhicules en location", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Mettre un véhicule en location", new_vehicule_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vehicules/_confirm_booking.html.erb
<h3>Votre réservation est confirmée.</h3>
<p> Vous allez recevoir un mail de confirmation avec les modalités pour contacter le propriétaire</p>

app/views/vehicules/_info_window.html.erb
<h3><%= vehicule.model %></h3>
<p><%= vehicule.address %></p>

app/views/vehicules/index.html.erb
<div class="category d-flex justify-content-center">
  <% [["Moto", "fa-solid fa-motorcycle"], ["Plat", "fa-solid fa-burger"], ["Char", "fa-solid fa-truck-monster"],
      ["Funny", "fa-solid fa-face-laugh-squint"]].each do |cat|  %>
    <%= link_to vehicules_path(query: cat[0]), class: "btn" do %>
      <span style="font-size:29px;"><i class="<%= cat[1] %>"></i></span>
    <% end %>

  <% end %>

  <%= link_to vehicules_path, class: "btn" do %>
    <i class="fa-solid fa-circle-xmark delete-icon"></i>
  <% end %>


    <%# <i class="fa-solid fa-circle-xmark"></i>
    <span style="font-size:29px"></span> %>

</div>

    <span style="font-size:29px"></span>

<div class="container card-container">

  <div class="row">
  <% @vehicules.each do |vehicule| %>
    <div class="col-12 col-sm-6 col-md-6 col-lg-4">

      <%= link_to vehicule_path(vehicule), style: "text-decoration: none; color: inherit;" do %>
        <div class="card-product">
          <div class="card-photo-title d-flex flex-column ">
            <%= cl_image_tag vehicule.photo.key, height: 200, width: 200,  class: "card_image" %>
            <h3 class="m-0" ><%= vehicule.model %></h3>
          </div>
          <div class="card-text d-flex align-items-center">
            <p><%= vehicule.description %></p>
          </div>
          <strong> <p class="m-0"><%= vehicule.prix %> euros</p></strong>
        </div>
      <% end %>


   </div>
  <% end %>
  </div>

  <div class="col-lg-4 mx-3">


  <div style="width: 100%; height: 600px;"
  id="map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
</div>

app/views/vehicules/new.html.erb
<div class="container">
  <div class="my-3">
        <h2>Ajoutez votre véhicule à la location</h2>
  </div>
    <div class="vehicle_grid">
      <div class="vehicle_item1">
        <div class="form my-5">
          <%= simple_form_for(@vehicule) do |f| %>
          <%= f.input :category, label: 'Catégorie'%>
          <%= f.input :model, label: 'Modèle'%>
          <%= f.input :description, label: 'Décris nous ton bijou'%>
          <%= f.input :prix, label: 'Prix/jour' %>
          <%= f.input :photo, as: :file, label: 'Ajoute une photo de ton bolide' %>
          <%= f.submit class:"btn btn-warning btn-lg"%>
          <% end %>
        </div>
      </div>

        <div><%= image_tag "https://res.cloudinary.com/dwnuhlrsx/image/upload/v1700839231/production/ajout1.jpg", size: "280x290" %></div>
        <div> <%= image_tag "https://res.cloudinary.com/dwnuhlrsx/image/upload/v1700839184/production/ajout2.jpg", size: "280x290" %></div>
  </div>
</div>

app/views/vehicules/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 col-md-6 col-lg-4">

        <div class="card-product card-product-show">
          <div class="card-photo-title d-flex flex-column ">
            <%= cl_image_tag @vehicule.photo.key, height: 250, width: 250,  class: "card_image" %>
            <h3 class="m-0" ><%= @vehicule.model %></h3>
          </div>
          <div class="card-text d-flex align-items-center">
            <p><%= @vehicule.description %></p>
          </div>
          <strong> <p class="m-0"><%= @vehicule.prix %> euros</p></strong>
        </div>
    </div>
    <!-- Card Véhicule  -->
    <!-- Contenu du new booking -->
    <div class="col-lg-4 col-xs-12">
      <div class="text-center">
        <h3>Faites-vous plaisir</h3>
        <div class="booking" data-controller="toggle" >
          <div class="btn  btn-warning d-none" id="resabtn" data-action="click->toggle#fire" data-toggle-target="togglablebookingElement">
            réservation
          </div>
          <div data-toggle-target="togglableElement" >
            <div class="form-wrapper text-center">
              <h2>Réserver un véhicule</h2>
              <%= simple_form_for [@vehicule, @booking], input_html: { class: "m-auto w-50 flex " } do |f| %>
                <%= f.input :date_resa,
                              label: "Votre période de location",
                              as: :string,
                              required: false,
                              input_html: { data: { controller: "datepicker" }, class: "d-none w-50 "}  %>
                <%= f.submit "Réserver" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>